name:                qxo
version:             0.1.0.0
github:              "callmecabman/qxo"
license:             BSD3
author:              "callmecabman"
maintainer:          "callmecabman@protonmail.ch"
copyright:           "2018 callmecabman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/callmecabman/qxo#readme>

dependencies:
- base >= 4.7 && < 5
- fgl

library:
  source-dirs: src

executables:
  qxo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qxo
    - fgl

tests:
  qxo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qxo
